name = "rin-server"
main = "server/src/_worker.ts"
compatibility_date = "2024-05-29"
node_compat = true

[triggers]
crons = ["*/20 * * * *"]

[vars]
FRONTEND_URL = "https://ra2.qyjoy.vip"
S3_FOLDER = "images/"
S3_CACHE_FOLDER = "cache/"
S3_REGION = "auto"
S3_ENDPOINT = "https://30f95ced9e5a54aca838e5c15b6f338c.r2.cloudflarestorage.com"           # 必填：S3 兼容存储的 endpoint
S3_ACCESS_HOST = "https://r2.qyjoy.vip"     # 必填：S3 资源外链主机
S3_BUCKET = "ra2blog"                  # 必填：S3 存储桶名
S3_FORCE_PATH_STYLE = "false"
WEBHOOK_URL = "https://<YOUR_WEBHOOK_URL>"           # 可选：外部 webhook
RSS_TITLE = "Rin Development Environment"
RSS_DESCRIPTION = "Development Environment"

[[d1_databases]]
binding = "DB"
database_name = "rin"
database_id = "61f65142-9b7e-4208-a8c9-0c3907f10938"
