#:schema node_modules/wrangler/config-schema.json
name = "ra2blog-server"
main = "server/src/_worker.ts"
compatibility_date = "2024-05-29"
# compatibility_flags = ["nodejs_compat"]
node_compat = true

[triggers]
crons = ["*/20 * * * *"]

[vars]
FRONTEND_URL = "https://ra2.qyjoy.vip"
S3_FOLDER = "images/"
S3_CACHE_FOLDER="cache/"
S3_REGION = "auto"
S3_ENDPOINT = "<YourS3Endpoint>"
S3_ACCESS_HOST = "<YourS3AccessHost>"
S3_BUCKET = "<YourS3BucketName>"
S3_FORCE_PATH_STYLE = "false"
WEBHOOK_URL = "https://<YourWebhookURL>"
RSS_TITLE = "Rin Development Environment"
RSS_DESCRIPTION = "Development Environment"

[[d1_databases]]
binding = "DB"
database_name = "rin"
database_id = "61f65142-9b7e-4208-a8c9-0c3907f10938"
